# Generated by Django 6.0.3 on 2026-03-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('Student_ID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('YearOfStudy', models.IntegerField()),
                ('TeamName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('EntryExit_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EntryTime', models.DateTimeField(null=True)),
                ('ExitTime', models.DateTimeField(null=True)),
                ('TimeSpent', models.DurationField(null=True)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracktimeapp.timeentry')),
            ],
        ),
    ]
