# Generated by Django 6.0.3 on 2026-03-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracktimeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeEntry',
            new_name='Members',
        ),
    ]
