# Generated by Django 6.0.3 on 2026-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktimeapp', '0002_rename_timeentry_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='ExitTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='TimeSpent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
